package mavtrainticket

// Code was originally generated by kaitai-struct-compiler from a .ksy source file, and modified afterwards.

import (
	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
	"io"
	"bytes"
)

type MavTrainTicketEnvelope struct {
	Version uint8
	SignatureVersion uint8
	TicketId string
	RicsCode string
	RawPayload []byte
	Signature []byte
	_io *kaitai.Stream
	_root *MavTrainTicketEnvelope
	_parent kaitai.Struct
	_raw_gzip []byte
	_f_gzip bool
	gzip *Gzip
}
func NewMavTrainTicketEnvelope() *MavTrainTicketEnvelope {
	return &MavTrainTicketEnvelope{
	}
}

func (this MavTrainTicketEnvelope) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketEnvelope) Read(io *kaitai.Stream, parent kaitai.Struct, root *MavTrainTicketEnvelope) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.Version = tmp1
	if !(this.Version >= 2) {
		return kaitai.NewValidationLessThanError(2, this.Version, this._io, "/seq/0")
	}
	if !(this.Version <= 6) {
		return kaitai.NewValidationGreaterThanError(6, this.Version, this._io, "/seq/0")
	}
	tmp2, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.SignatureVersion = tmp2
	if (this.Version >= 5) {
		tmp3, err := this._io.ReadBytes(int(18))
		if err != nil {
			return err
		}
		tmp3 = kaitai.BytesTerminate(tmp3, 0, false)
		this.TicketId = string(tmp3)
	}
	if (this.Version >= 5) {
		tmp4, err := this._io.ReadBytes(int(4))
		if err != nil {
			return err
		}
		tmp4 = kaitai.BytesTerminate(tmp4, 0, false)
		this.RicsCode = string(tmp4)
	}
	tmp5, err := this._io.Size()
	if err != nil {
		return err
	}
	var tmp6 int64;
	if (this.Version >= 5) {
		tmp6 = 24 + 56
	} else {
		tmp6 = 2 + 256
	}
	tmp7, err := this._io.ReadBytes(int(tmp5 - tmp6))
	if err != nil {
		return err
	}
	tmp7 = tmp7
	this.RawPayload = tmp7
	var tmp8 int64;
	if (this.Version >= 5) {
		tmp8 = 56
	} else {
		tmp8 = 256
	}
	tmp9, err := this._io.ReadBytes(int(tmp8))
	if err != nil {
		return err
	}
	tmp9 = tmp9
	this.Signature = tmp9
	return err
}
func (this *MavTrainTicketEnvelope) Gzip() (v *Gzip, err error) {
	if (this._f_gzip) {
		return this.gzip, nil
	}
	this._f_gzip = true
	_pos, err := this._io.Pos()
	if err != nil {
		return nil, err
	}
	var tmp10 int8;
	if (this.Version >= 5) {
		tmp10 = 24
	} else {
		tmp10 = 2
	}
	_, err = this._io.Seek(int64(tmp10), io.SeekStart)
	if err != nil {
		return nil, err
	}
	tmp11, err := this._io.Size()
	if err != nil {
		return nil, err
	}
	var tmp12 int64;
	if (this.Version >= 5) {
		tmp12 = 24 + 56
	} else {
		tmp12 = 2 + 256
	}
	tmp13, err := this._io.ReadBytes(int(tmp11 - tmp12))
	if err != nil {
		return nil, err
	}
	tmp13 = tmp13
	this._raw_gzip = tmp13
	_io__raw_gzip := kaitai.NewStream(bytes.NewReader(this._raw_gzip))
	tmp14 := NewGzip()
	err = tmp14.Read(_io__raw_gzip, nil, nil)
	if err != nil {
		return nil, err
	}
	this.gzip = tmp14
	_, err = this._io.Seek(_pos, io.SeekStart)
	if err != nil {
		return nil, err
	}
	return this.gzip, nil
}
