package mavtrainticket

// Code was originally generated by kaitai-struct-compiler from a .ksy source file, and modified afterwards.

import (
	"time"

	"github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"
)

type Payload struct {
	Header                *Header                 `json:"header"`
	PersonBlock           *PersonBlock            `json:"person_block"`
	TripBlock             *TripBlock              `json:"trip_block"`
	ClassUpgradeBlocks    []*ClassUpgradeBlock    `json:"class_upgrade_blocks,omitempty"`
	SeatReservationBlocks []*SeatReservationBlock `json:"seat_reservation_blocks,omitempty"`
	PassBlocks            []*PassBlock            `json:"pass_blocks,omitempty"`
	Version               uint8                   `json:"version"`
	_io                   *kaitai.Stream
	_root                 *Payload
	_parent               kaitai.Struct
}

func NewPayload(version uint8) *Payload {
	return &Payload{
		Version: version,
	}
}

func (this Payload) IO_() *kaitai.Stream {
	return this._io
}

func (this *Payload) Read(io *kaitai.Stream, parent kaitai.Struct, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewHeader(this.Version)
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	if this.Header.Flags.PersonBlockPresent == true {
		tmp2 := NewPersonBlock()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.PersonBlock = tmp2
	}
	if this.Header.Flags.TripBlockPresent == true {
		tmp3 := NewTripBlock(this.Version)
		err = tmp3.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.TripBlock = tmp3
	}
	for i := 0; i < int(this.Header.NumClassUpgradeBlocks); i++ {
		_ = i
		tmp4 := NewClassUpgradeBlock(this.Version)
		err = tmp4.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.ClassUpgradeBlocks = append(this.ClassUpgradeBlocks, tmp4)
	}
	for i := 0; i < int(this.Header.NumSeatReservationBlocks); i++ {
		_ = i
		tmp5 := NewSeatReservationBlock(this.Version)
		err = tmp5.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.SeatReservationBlocks = append(this.SeatReservationBlocks, tmp5)
	}
	for i := 0; i < int(this.Header.NumPassBlocks); i++ {
		_ = i
		tmp6 := NewPassBlock(this.Version)
		err = tmp6.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.PassBlocks = append(this.PassBlocks, tmp6)
	}
	return err
}

type AppliedDiscounts struct {
	Tag     uint32 `json:"tag"`
	_io     *kaitai.Stream
	_root   *Payload
	_parent kaitai.Struct
}

func NewAppliedDiscounts() *AppliedDiscounts {
	return &AppliedDiscounts{}
}

func (this AppliedDiscounts) IO_() *kaitai.Stream {
	return this._io
}

func (this *AppliedDiscounts) Read(io *kaitai.Stream, parent kaitai.Struct, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp6, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Tag = uint32(tmp6)
	return err
}

/**
 * The date of birth is packed into a 32 bit integer with the formula:
 *   year * 10000 + month * 100 + day
 */
type BirthDate struct {
	Packed   uint32 `json:"packed"`
	_io      *kaitai.Stream
	_root    *Payload
	_parent  *PersonBlock
	_f_day   bool
	Day      int `json:"day"`
	_f_month bool
	Month    int `json:"month"`
	_f_year  bool
	Year     int `json:"year"`
}

func NewBirthDate() *BirthDate {
	return &BirthDate{}
}

func (this BirthDate) IO_() *kaitai.Stream {
	return this._io
}

func (this *BirthDate) Read(io *kaitai.Stream, parent *PersonBlock, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp6, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Packed = uint32(tmp6)

	this.Year = int(this.Packed / 10000)
	this.Month = int((int(this.Packed) - this.Year*10000) / 100)
	this.Day = int((int(this.Packed) - this.Year*10000) - this.Month*100)

	return err
}

type ClassUpgradeBlock struct {
	DepartureStation *StationId
	DestinationStation *StationId
	Class string
	TicketKind *TicketKind
	ValidStartAt *Timestamp
	ValidInterval *ValidInterval
	NumPassengers uint8
	AppliedDiscounts *AppliedDiscounts
	Version uint8
	_io *kaitai.Stream
	_root *Payload
	_parent *Payload
}
func NewClassUpgradeBlock(version uint8) *ClassUpgradeBlock {
	return &ClassUpgradeBlock{
		Version: version,
	}
}

func (this ClassUpgradeBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *ClassUpgradeBlock) Read(io *kaitai.Stream, parent *Payload, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp12 := NewStationId(this.Version)
	err = tmp12.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DepartureStation = tmp12
	tmp13 := NewStationId(this.Version)
	err = tmp13.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DestinationStation = tmp13
	tmp14, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp14 = tmp14
	this.Class = string(tmp14)
	tmp15 := NewTicketKind()
	err = tmp15.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketKind = tmp15
	tmp16 := NewTimestamp()
	err = tmp16.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidStartAt = tmp16
	tmp17 := NewValidInterval(this.Version)
	err = tmp17.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidInterval = tmp17
	tmp18, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassengers = tmp18
	tmp19 := NewAppliedDiscounts()
	err = tmp19.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AppliedDiscounts = tmp19
	return err
}

type Header struct {
	TicketId                 string       `json:"ticket_id"`
	RicsId                   uint16       `json:"rics_id"`
	IssuedAt                 *Timestamp   `json:"issued_at"`
	Price                    float32      `json:"price"`
	Flags                    *HeaderFlags `json:"flags"`
	NumClassUpgradeBlocks    uint8 `json:"num_class_upgrade_blocks"`
	NumSeatReservationBlocks uint8 `json:"num_seat_reservation_blocks"`
	NumPassBlocks            uint8 `json:"num_pass_blocks"`
	reserved0003             []byte
	TicketMedium             *TicketMedium `json:"ticket_medium"`
	Version                  uint8         `json:"version"`
	_io                      *kaitai.Stream
	_root                    *Payload
	_parent                  *Payload
}

func NewHeader(version uint8) *Header {
	return &Header{
		Version: version,
	}
}

func (this Header) IO_() *kaitai.Stream {
	return this._io
}

func (this *Header) Read(io *kaitai.Stream, parent *Payload, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	if this.Version <= 4 {
		tmp11, err := this._io.ReadBytes(int(18))
		if err != nil {
			return err
		}
		tmp11 = kaitai.BytesTerminate(tmp11, 0, false)
		this.TicketId = string(tmp11)
	}
	if this.Version <= 4 {
		tmp12, err := this._io.ReadU2be()
		if err != nil {
			return err
		}
		this.RicsId = uint16(tmp12)
	}
	tmp13 := NewTimestamp()
	err = tmp13.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.IssuedAt = tmp13
	tmp14, err := this._io.ReadF4be()
	if err != nil {
		return err
	}
	this.Price = float32(tmp14)
	tmp15 := NewHeaderFlags()
	err = tmp15.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp15
	tmp16, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumClassUpgradeBlocks = tmp16
	tmp17, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumSeatReservationBlocks = tmp17
	tmp18, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassBlocks = tmp18
	tmp19, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp19 = tmp19
	this.reserved0003 = tmp19
	tmp20 := NewTicketMedium()
	err = tmp20.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketMedium = tmp20
	return err
}

type HeaderFlags struct {
	PersonBlockPresent bool `json:"person_block_present"`
	reserved0001       uint64
	TripBlockPresent   bool `json:"trip_block_present"`
	_io                *kaitai.Stream
	_root              *Payload
	_parent            *Header
}

func NewHeaderFlags() *HeaderFlags {
	return &HeaderFlags{}
}

func (this HeaderFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *HeaderFlags) Read(io *kaitai.Stream, parent *Header, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp21, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.PersonBlockPresent = tmp21 != 0
	tmp22, err := this._io.ReadBitsIntBe(6)
	if err != nil {
		return err
	}
	this.reserved0001 = tmp22
	tmp23, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.TripBlockPresent = tmp23 != 0
	return err
}

type PassBlock struct {
	TicketKind        *TicketKind       `json:"ticket_kind"`
	AppliedDiscounts1 *AppliedDiscounts `json:"applied_discounts_1"`
	AppliedDiscounts2 *AppliedDiscounts `json:"applied_discounts_2"`
	ValidStartAt      *Timestamp        `json:"valid_start_at"`
	ValidInterval     *ValidInterval    `json:"valid_interval"`
	NumPassengers     uint8             `json:"num_passengers"`
	Version           uint8             `json:"version"`
	_io               *kaitai.Stream
	_root             *Payload
	_parent           *Payload
}

func NewPassBlock(version uint8) *PassBlock {
	return &PassBlock{
		Version: version,
	}
}

func (this PassBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *PassBlock) Read(io *kaitai.Stream, parent *Payload, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp24 := NewTicketKind()
	err = tmp24.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketKind = tmp24
	tmp25 := NewAppliedDiscounts()
	err = tmp25.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AppliedDiscounts1 = tmp25
	tmp26 := NewAppliedDiscounts()
	err = tmp26.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AppliedDiscounts2 = tmp26
	tmp27 := NewTimestamp()
	err = tmp27.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidStartAt = tmp27
	tmp28 := NewValidInterval(this.Version)
	err = tmp28.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidInterval = tmp28
	tmp29, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassengers = tmp29
	return err
}

type PersonBlock struct {
	Name         string     `json:"name"`
	BirthDate    *BirthDate `json:"birth_date"`
	IdCardNumber string     `json:"id_card_number"`
	_io          *kaitai.Stream
	_root        *Payload
	_parent      *Payload
}

func NewPersonBlock() *PersonBlock {
	return &PersonBlock{}
}

func (this PersonBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *PersonBlock) Read(io *kaitai.Stream, parent *Payload, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp30, err := this._io.ReadBytes(int(45))
	if err != nil {
		return err
	}
	tmp30 = kaitai.BytesTerminate(tmp30, 0, false)
	this.Name = string(tmp30)
	tmp31 := NewBirthDate()
	err = tmp31.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.BirthDate = tmp31
	tmp32, err := this._io.ReadBytes(int(15))
	if err != nil {
		return err
	}
	tmp32 = kaitai.BytesTerminate(tmp32, 0, false)
	this.IdCardNumber = string(tmp32)
	return err
}

/**
 * Often omitted, mostly relevant for passes
 */
type SeatReservationBlock struct {
	DepartureStation   *StationId  `json:"departure_station"`
	DestinationStation *StationId  `json:"destination_station"`
	TicketKind         *TicketKind `json:"ticket_kind"`
	TravelTime         *Timestamp  `json:"travel_time"`
	RicsCode           uint16      `json:"rics_code"`
	TrainNumber        string      `json:"train_number"`
	NumPassengers      uint8       `json:"num_passengers"`
	CarNumber          string      `json:"car_number"`
	SeatNumber         uint16      `json:"seat_number"`
	SeatNumber2        uint16      `json:"seat_number2"`
	reserved           []byte
	Version            uint8 `json:"version"`
	_io                *kaitai.Stream
	_root              *Payload
	_parent            *Payload
}

func NewSeatReservationBlock(version uint8) *SeatReservationBlock {
	return &SeatReservationBlock{
		Version: version,
	}
}

func (this SeatReservationBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *SeatReservationBlock) Read(io *kaitai.Stream, parent *Payload, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp33 := NewStationId(this.Version)
	err = tmp33.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DepartureStation = tmp33
	tmp34 := NewStationId(this.Version)
	err = tmp34.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DestinationStation = tmp34
	tmp35 := NewTicketKind()
	err = tmp35.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketKind = tmp35
	tmp36 := NewTimestamp()
	err = tmp36.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TravelTime = tmp36
	tmp37, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.RicsCode = uint16(tmp37)
	var tmp38 int8
	if this.Version >= 6 {
		tmp38 = 20
	} else {
		tmp38 = 5
	}
	tmp39, err := this._io.ReadBytes(int(tmp38))
	if err != nil {
		return err
	}
	tmp39 = kaitai.BytesTerminate(tmp39, 0, false)
	this.TrainNumber = string(tmp39)
	tmp40, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassengers = tmp40
	tmp41, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp41 = kaitai.BytesTerminate(tmp41, 0, false)
	this.CarNumber = string(tmp41)
	tmp42, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SeatNumber = uint16(tmp42)
	tmp43, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SeatNumber2 = uint16(tmp43)
	tmp44, err := this._io.ReadBytes(int(28))
	if err != nil {
		return err
	}
	tmp44 = tmp44
	this.reserved = tmp44
	return err
}

type StationId struct {
	Id      uint64 `json:"id"`
	Name    string `json:"name"`
	Version uint8  `json:"version"`
	_io     *kaitai.Stream
	_root   *Payload
	_parent kaitai.Struct
}

func NewStationId(version uint8) *StationId {
	return &StationId{
		Version: version,
	}
}

func (this StationId) IO_() *kaitai.Stream {
	return this._io
}

func (this *StationId) Read(io *kaitai.Stream, parent kaitai.Struct, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp45, err := this._io.ReadBitsIntBe(24)
	if err != nil {
		return err
	}
	this.Id = tmp45

	found := false
	if this.Version <= 4 {
		this.Name, found = uicStationNames[this.Id]
		if !found {
			this.Name, found = mavStationNames[this.Id]
		}
	} else {
		this.Name, found = mavStationNames[this.Id]
		if !found {
			this.Name, found = uicStationNames[this.Id]
		}
	}

	return err
}

type TicketKindKnownValues int

const (
	TicketKindKnownValues__Helyjegy TicketKindKnownValues = 1941101165
	TicketKindKnownValues__Potjegy  TicketKindKnownValues = 4050207847
)

var values_TicketKindKnownValues = map[TicketKindKnownValues][numLangs]string{
	0xf1694467: [numLangs]string{"surcharge", "Surcharge", "Pótdíj" },
	0x73b2da6d: [numLangs]string{"seat_reservation", "Seat reservation", "Helyjegy" },
}

func (v TicketKindKnownValues) ToString(l Language) string {
	if l >= numLangs {
		l = 0
	}
	s, found := values_TicketKindKnownValues[v]
	if ! found {
		return ""
	}
	return s[l]
}

type TicketKind struct {
	Tag     TicketKindKnownValues `json:"tag"`
	Name    string                `json:"name"`
	_io     *kaitai.Stream
	_root   *Payload
	_parent kaitai.Struct
}

func NewTicketKind() *TicketKind {
	return &TicketKind{}
}

func (this TicketKind) IO_() *kaitai.Stream {
	return this._io
}

func (this *TicketKind) Read(io *kaitai.Stream, parent kaitai.Struct, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp46, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Tag = TicketKindKnownValues(tmp46)
	this.Name = this.Tag.ToString(0)
	return err
}

type TicketMediumKnownValues int

const (
	TicketMediumKnownValues__ElectronicPdfFromApp            TicketMediumKnownValues = 594347296
	TicketMediumKnownValues__ElectronicPdfFromWeb            TicketMediumKnownValues = 864524286
	TicketMediumKnownValues__ThermalPaperFromEmke            TicketMediumKnownValues = 1420145485
	TicketMediumKnownValues__HologramPaperFromVolanbusz      TicketMediumKnownValues = 1763413351
	TicketMediumKnownValues__PaperFromVendingMachine         TicketMediumKnownValues = 2815794854
	TicketMediumKnownValues__PaperBkkPass                    TicketMediumKnownValues = 3347428876
	TicketMediumKnownValues__ThermalPaperFromTicketInspector TicketMediumKnownValues = 4172547533
)

var values_TicketMediumKnownValues = map[TicketMediumKnownValues][numLangs]string{
	0x236d0520: [numLangs]string{
		"electronic_pdf_from_app",
		"PDF from app",
		"PDF az appból" },
	0x54a5b34d: [numLangs]string{
		"thermal_paper_from_emke",
		"Thermal paper from EMKE",
		"Hőpapír EMKE nyomtatóból" },
	0x691b8d67: [numLangs]string{
		"hologram_paper_from_volanbusz",
		"Hologram paper from Volanbusz",
		"Hologramos papír a Volánbusztól" },
	0xa7d59ea6: [numLangs]string{
		"paper_from_vending_machine",
		"Paper from vending machine",
		"Papír a jegykiadó automatából" },
	0xc785b60c: [numLangs]string{
		"paper_bkk_pass",
		"Paper BKK pass",
		"Papír BKK bérlet" },
	0x338797fe: [numLangs]string{
		"electronic_pdf_from_web",
		"PDF from MAV website",
		"PDF a MÁV honlapjáról" },
	0xf8b405cd: [numLangs]string{
		"thermal_paper_from_ticket_inspector",
		"Thermal paper from ticket inspector",
		"Hőpapír a jegykezelőtől" },
}

func (v TicketMediumKnownValues) ToString(l Language) string {
	if l >= numLangs {
		l = 0
	}
	s, found := values_TicketMediumKnownValues[v]
	if ! found {
		return ""
	}
	return s[l]
}

type TicketMedium struct {
	Tag     TicketMediumKnownValues `json:"tag"`
	Name    string                  `json:"name"`
	_io     *kaitai.Stream
	_root   *Payload
	_parent *Header
}

func NewTicketMedium() *TicketMedium {
	return &TicketMedium{}
}

func (this TicketMedium) IO_() *kaitai.Stream {
	return this._io
}

func (this *TicketMedium) Read(io *kaitai.Stream, parent *Header, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp47, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Tag = TicketMediumKnownValues(tmp47)
	this.Name = this.Tag.ToString(0)
	return err
}

/**
 * Timestamps are represented as the number of seconds since
 * 2017-01-01T00:00:00+01:00, as 32 bit integer.
 */
type Timestamp struct {
	SecondsSince2017    uint32 `json:"seconds_since_2017"`
	_io                 *kaitai.Stream
	_root               *Payload
	_parent             kaitai.Struct
	_f_secondsSince1970 bool
	SecondsSince1970    int `json:"seconds_since_1970"`
}

func NewTimestamp() *Timestamp {
	return &Timestamp{}
}

func (this Timestamp) IO_() *kaitai.Stream {
	return this._io
}

func (this *Timestamp) Read(io *kaitai.Stream, parent kaitai.Struct, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp48, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.SecondsSince2017 = uint32(tmp48)

	this.SecondsSince1970 = int(this.SecondsSince2017 + 1483225200)

	return err
}

func (this *Timestamp) String() string {
	tz, _ := time.LoadLocation("Europe/Budapest")
	t := time.Unix(int64(this.SecondsSince1970), 0)
	return t.In(tz).Format(time.DateTime)
}

type TripBlock struct {
	TicketKind         *TicketKind       `json:"ticket_kind"`
	DepartureStation   *StationId        `json:"departure_station"`
	DestinationStation *StationId        `json:"destination_station"`
	ViaStations        []*StationId      `json:"via_stations,omitempty"`
	Class              string            `json:"class"`
	IsRealTicket       uint8             `json:"is_real_ticket"`
	ValidStartAt       *Timestamp        `json:"valid_startat"`
	ValidInterval      *ValidInterval    `json:"valid_interval"`
	NumPassengers      uint8             `json:"num_passengers"`
	AppliedDiscounts   *AppliedDiscounts `json:"applied_discounts"`
	Version            uint8             `json:"version"`
	_io                *kaitai.Stream
	_root              *Payload
	_parent            *Payload
}

func NewTripBlock(version uint8) *TripBlock {
	return &TripBlock{
		Version: version,
	}
}

func (this TripBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *TripBlock) Read(io *kaitai.Stream, parent *Payload, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp49 := NewTicketKind()
	err = tmp49.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketKind = tmp49
	tmp50 := NewStationId(this.Version)
	err = tmp50.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DepartureStation = tmp50
	tmp51 := NewStationId(this.Version)
	err = tmp51.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DestinationStation = tmp51
	for i := 0; i < int(30); i++ {
		_ = i
		tmp52 := NewStationId(this.Version)
		err = tmp52.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		if tmp52.Id != 0 {
			this.ViaStations = append(this.ViaStations, tmp52)
		}
	}
	tmp53, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp53 = tmp53
	this.Class = string(tmp53)
	tmp54, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IsRealTicket = tmp54
	tmp55 := NewTimestamp()
	err = tmp55.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidStartAt = tmp55
	tmp56 := NewValidInterval(this.Version)
	err = tmp56.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidInterval = tmp56
	tmp57, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassengers = tmp57
	tmp58 := NewAppliedDiscounts()
	err = tmp58.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AppliedDiscounts = tmp58
	return err
}

type ValidInterval struct {
	Minutes int   `json:"minutes"`
	Version uint8 `json:"version"`
	_io     *kaitai.Stream
	_root   *Payload
	_parent kaitai.Struct
}

func NewValidInterval(version uint8) *ValidInterval {
	return &ValidInterval{
		Version: version,
	}
}

func (this ValidInterval) IO_() *kaitai.Stream {
	return this._io
}

func (this *ValidInterval) Read(io *kaitai.Stream, parent kaitai.Struct, root *Payload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	switch this.Version {
	case 2:
		tmp59, err := this._io.ReadU2be()
		if err != nil {
			return err
		}
		this.Minutes = int(tmp59)
	case 3:
		tmp60, err := this._io.ReadU2be()
		if err != nil {
			return err
		}
		this.Minutes = int(tmp60)
	default:
		tmp61, err := this._io.ReadBitsIntBe(24)
		if err != nil {
			return err
		}
		this.Minutes = int(tmp61)
	}
	return err
}

func (this *ValidInterval) AsTimestamp(start *Timestamp) string {
	tz, _ := time.LoadLocation("Europe/Budapest")
	t := time.Unix(int64(start.SecondsSince1970 + this.Minutes * 60), 0)
	return t.In(tz).Format(time.DateTime)
}
