package mavtrainticket

// Code was originally generated by kaitai-struct-compiler from a .ksy source file, and modified afterwards.

import "github.com/kaitai-io/kaitai_struct_go_runtime/kaitai"

type MavTrainTicketPayload struct {
	Header *MavTrainTicketPayload_Header
	PersonBlock *MavTrainTicketPayload_PersonBlock
	TripBlock *MavTrainTicketPayload_TripBlock
	SeatReservationBlocks []*MavTrainTicketPayload_SeatReservationBlock
	PassBlocks []*MavTrainTicketPayload_PassBlock
	Version uint8
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent kaitai.Struct
}
func NewMavTrainTicketPayload(version uint8) *MavTrainTicketPayload {
	return &MavTrainTicketPayload{
		Version: version,
	}
}

func (this MavTrainTicketPayload) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload) Read(io *kaitai.Stream, parent kaitai.Struct, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp1 := NewMavTrainTicketPayload_Header(this.Version)
	err = tmp1.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Header = tmp1
	if (this.Header.Flags.PersonBlockPresent == true) {
		tmp2 := NewMavTrainTicketPayload_PersonBlock()
		err = tmp2.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.PersonBlock = tmp2
	}
	if (this.Header.Flags.TripBlockPresent == true) {
		tmp3 := NewMavTrainTicketPayload_TripBlock(this.Version)
		err = tmp3.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.TripBlock = tmp3
	}
	for i := 0; i < int(this.Header.NumSeatReservationBlocks); i++ {
		_ = i
		tmp4 := NewMavTrainTicketPayload_SeatReservationBlock(this.Version)
		err = tmp4.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.SeatReservationBlocks = append(this.SeatReservationBlocks, tmp4)
	}
	for i := 0; i < int(this.Header.NumPassBlocks); i++ {
		_ = i
		tmp5 := NewMavTrainTicketPayload_PassBlock(this.Version)
		err = tmp5.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		this.PassBlocks = append(this.PassBlocks, tmp5)
	}
	return err
}
type MavTrainTicketPayload_AppliedDiscounts struct {
	Tag uint32
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent kaitai.Struct
}
func NewMavTrainTicketPayload_AppliedDiscounts() *MavTrainTicketPayload_AppliedDiscounts {
	return &MavTrainTicketPayload_AppliedDiscounts{
	}
}

func (this MavTrainTicketPayload_AppliedDiscounts) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_AppliedDiscounts) Read(io *kaitai.Stream, parent kaitai.Struct, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp6, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Tag = uint32(tmp6)
	return err
}

/**
 * The date of birth is packed into a 32 bit integer with the formula:
 *   year * 10000 + month * 100 + day
 */
type MavTrainTicketPayload_BirthDate struct {
	Packed uint32
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload_PersonBlock
	_f_day bool
	Day int
	_f_month bool
	Month int
	_f_year bool
	Year int
}
func NewMavTrainTicketPayload_BirthDate() *MavTrainTicketPayload_BirthDate {
	return &MavTrainTicketPayload_BirthDate{
	}
}

func (this MavTrainTicketPayload_BirthDate) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_BirthDate) Read(io *kaitai.Stream, parent *MavTrainTicketPayload_PersonBlock, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp6, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Packed = uint32(tmp6)

	this.Year = int(this.Packed / 10000)
	this.Month = int((int(this.Packed) - this.Year * 10000) / 100)
	this.Day = int((int(this.Packed) - this.Year * 10000) - this.Month * 100)

	return err
}

type MavTrainTicketPayload_Header struct {
	TicketId string
	RicsId uint16
	IssuedAt *MavTrainTicketPayload_Timestamp
	Price float32
	Flags *MavTrainTicketPayload_HeaderFlags
	reserved0002 uint8
	NumSeatReservationBlocks uint8
	NumPassBlocks uint8
	reserved0003 []byte
	TicketMedium *MavTrainTicketPayload_TicketMedium
	Version uint8
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload
}
func NewMavTrainTicketPayload_Header(version uint8) *MavTrainTicketPayload_Header {
	return &MavTrainTicketPayload_Header{
		Version: version,
	}
}

func (this MavTrainTicketPayload_Header) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_Header) Read(io *kaitai.Stream, parent *MavTrainTicketPayload, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	if (this.Version <= 4) {
		tmp11, err := this._io.ReadBytes(int(18))
		if err != nil {
			return err
		}
		tmp11 = kaitai.BytesTerminate(tmp11, 0, false)
		this.TicketId = string(tmp11)
	}
	if (this.Version <= 4) {
		tmp12, err := this._io.ReadU2be()
		if err != nil {
			return err
		}
		this.RicsId = uint16(tmp12)
	}
	tmp13 := NewMavTrainTicketPayload_Timestamp()
	err = tmp13.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.IssuedAt = tmp13
	tmp14, err := this._io.ReadF4be()
	if err != nil {
		return err
	}
	this.Price = float32(tmp14)
	tmp15 := NewMavTrainTicketPayload_HeaderFlags()
	err = tmp15.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.Flags = tmp15
	tmp16, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.reserved0002 = tmp16
	tmp17, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumSeatReservationBlocks = tmp17
	tmp18, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassBlocks = tmp18
	tmp19, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp19 = tmp19
	this.reserved0003 = tmp19
	tmp20 := NewMavTrainTicketPayload_TicketMedium()
	err = tmp20.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketMedium = tmp20
	return err
}
type MavTrainTicketPayload_HeaderFlags struct {
	PersonBlockPresent bool
	reserved0001 uint64
	TripBlockPresent bool
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload_Header
}
func NewMavTrainTicketPayload_HeaderFlags() *MavTrainTicketPayload_HeaderFlags {
	return &MavTrainTicketPayload_HeaderFlags{
	}
}

func (this MavTrainTicketPayload_HeaderFlags) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_HeaderFlags) Read(io *kaitai.Stream, parent *MavTrainTicketPayload_Header, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp21, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.PersonBlockPresent = tmp21 != 0
	tmp22, err := this._io.ReadBitsIntBe(6)
	if err != nil {
		return err
	}
	this.reserved0001 = tmp22
	tmp23, err := this._io.ReadBitsIntBe(1)
	if err != nil {
		return err
	}
	this.TripBlockPresent = tmp23 != 0
	return err
}
type MavTrainTicketPayload_PassBlock struct {
	TicketKind *MavTrainTicketPayload_TicketKind
	AppliedDiscounts1 *MavTrainTicketPayload_AppliedDiscounts
	AppliedDiscounts2 *MavTrainTicketPayload_AppliedDiscounts
	TravelTime *MavTrainTicketPayload_Timestamp
	ValidInterval *MavTrainTicketPayload_ValidInterval
	NumPassengers uint8
	Version uint8
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload
}
func NewMavTrainTicketPayload_PassBlock(version uint8) *MavTrainTicketPayload_PassBlock {
	return &MavTrainTicketPayload_PassBlock{
		Version: version,
	}
}

func (this MavTrainTicketPayload_PassBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_PassBlock) Read(io *kaitai.Stream, parent *MavTrainTicketPayload, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp24 := NewMavTrainTicketPayload_TicketKind()
	err = tmp24.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketKind = tmp24
	tmp25 := NewMavTrainTicketPayload_AppliedDiscounts()
	err = tmp25.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AppliedDiscounts1 = tmp25
	tmp26 := NewMavTrainTicketPayload_AppliedDiscounts()
	err = tmp26.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AppliedDiscounts2 = tmp26
	tmp27 := NewMavTrainTicketPayload_Timestamp()
	err = tmp27.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TravelTime = tmp27
	tmp28 := NewMavTrainTicketPayload_ValidInterval(this.Version)
	err = tmp28.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidInterval = tmp28
	tmp29, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassengers = tmp29
	return err
}
type MavTrainTicketPayload_PersonBlock struct {
	Name string
	BirthDate *MavTrainTicketPayload_BirthDate
	IdCardNumber string
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload
}
func NewMavTrainTicketPayload_PersonBlock() *MavTrainTicketPayload_PersonBlock {
	return &MavTrainTicketPayload_PersonBlock{
	}
}

func (this MavTrainTicketPayload_PersonBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_PersonBlock) Read(io *kaitai.Stream, parent *MavTrainTicketPayload, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp30, err := this._io.ReadBytes(int(45))
	if err != nil {
		return err
	}
	tmp30 = kaitai.BytesTerminate(tmp30, 0, false)
	this.Name = string(tmp30)
	tmp31 := NewMavTrainTicketPayload_BirthDate()
	err = tmp31.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.BirthDate = tmp31
	tmp32, err := this._io.ReadBytes(int(15))
	if err != nil {
		return err
	}
	tmp32 = kaitai.BytesTerminate(tmp32, 0, false)
	this.IdCardNumber = string(tmp32)
	return err
}

/**
 * Often omitted, mostly relevant for passes
 */
type MavTrainTicketPayload_SeatReservationBlock struct {
	DepartureStation *MavTrainTicketPayload_StationId
	DestinationStation *MavTrainTicketPayload_StationId
	TicketKind *MavTrainTicketPayload_TicketKind
	TravelTime *MavTrainTicketPayload_Timestamp
	RicsCode uint16
	TrainNumber string
	NumPassengers uint8
	CarNumber string
	SeatNumber uint16
	SeatNumber2 uint16
	reserved []byte
	Version uint8
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload
}
func NewMavTrainTicketPayload_SeatReservationBlock(version uint8) *MavTrainTicketPayload_SeatReservationBlock {
	return &MavTrainTicketPayload_SeatReservationBlock{
		Version: version,
	}
}

func (this MavTrainTicketPayload_SeatReservationBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_SeatReservationBlock) Read(io *kaitai.Stream, parent *MavTrainTicketPayload, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp33 := NewMavTrainTicketPayload_StationId(this.Version)
	err = tmp33.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DepartureStation = tmp33
	tmp34 := NewMavTrainTicketPayload_StationId(this.Version)
	err = tmp34.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DestinationStation = tmp34
	tmp35 := NewMavTrainTicketPayload_TicketKind()
	err = tmp35.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketKind = tmp35
	tmp36 := NewMavTrainTicketPayload_Timestamp()
	err = tmp36.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TravelTime = tmp36
	tmp37, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.RicsCode = uint16(tmp37)
	var tmp38 int8;
	if (this.Version >= 6) {
		tmp38 = 20
	} else {
		tmp38 = 5
	}
	tmp39, err := this._io.ReadBytes(int(tmp38))
	if err != nil {
		return err
	}
	tmp39 = kaitai.BytesTerminate(tmp39, 0, false)
	this.TrainNumber = string(tmp39)
	tmp40, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassengers = tmp40
	tmp41, err := this._io.ReadBytes(int(3))
	if err != nil {
		return err
	}
	tmp41 = kaitai.BytesTerminate(tmp41, 0, false)
	this.CarNumber = string(tmp41)
	tmp42, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SeatNumber = uint16(tmp42)
	tmp43, err := this._io.ReadU2be()
	if err != nil {
		return err
	}
	this.SeatNumber2 = uint16(tmp43)
	tmp44, err := this._io.ReadBytes(int(28))
	if err != nil {
		return err
	}
	tmp44 = tmp44
	this.reserved = tmp44
	return err
}
type MavTrainTicketPayload_StationId struct {
	Id uint64
	Name string
	Version uint8
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent kaitai.Struct
}
func NewMavTrainTicketPayload_StationId(version uint8) *MavTrainTicketPayload_StationId {
	return &MavTrainTicketPayload_StationId{
		Version: version,
	}
}

func (this MavTrainTicketPayload_StationId) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_StationId) Read(io *kaitai.Stream, parent kaitai.Struct, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp45, err := this._io.ReadBitsIntBe(24)
	if err != nil {
		return err
	}
	this.Id = tmp45
	return err
}

type MavTrainTicketPayload_TicketKind_TicketKindKnownValues int
const (
	MavTrainTicketPayload_TicketKind_TicketKindKnownValues__Helyjegy MavTrainTicketPayload_TicketKind_TicketKindKnownValues = 1941101165
	MavTrainTicketPayload_TicketKind_TicketKindKnownValues__Potjegy MavTrainTicketPayload_TicketKind_TicketKindKnownValues = 4050207847
)
var values_MavTrainTicketPayload_TicketKind_TicketKindKnownValues = map[MavTrainTicketPayload_TicketKind_TicketKindKnownValues]string{
	0xf1694467: "potjegy",
	0x73b2da6d: "helyjegy",
}
func (v MavTrainTicketPayload_TicketKind_TicketKindKnownValues) String() string {
	s, _ := values_MavTrainTicketPayload_TicketKind_TicketKindKnownValues[v]
	return s
}
type MavTrainTicketPayload_TicketKind struct {
	Tag  MavTrainTicketPayload_TicketKind_TicketKindKnownValues
	Name string
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent kaitai.Struct
}
func NewMavTrainTicketPayload_TicketKind() *MavTrainTicketPayload_TicketKind {
	return &MavTrainTicketPayload_TicketKind{
	}
}

func (this MavTrainTicketPayload_TicketKind) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_TicketKind) Read(io *kaitai.Stream, parent kaitai.Struct, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp46, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Tag = MavTrainTicketPayload_TicketKind_TicketKindKnownValues(tmp46)
	this.Name = this.Tag.String()
	return err
}

type MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues int
const (
	MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues__ElectronicPdfFromApp MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = 594347296
	MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues__ElectronicPdfFromWeb MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = 864524286
	MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues__ThermalPaperFromEmke MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = 1420145485
	MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues__HologramPaperFromVolanbusz MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = 1763413351
	MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues__PaperFromVendingMachine MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = 2815794854
	MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues__PaperBkkPass MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = 3347428876
	MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues__ThermalPaperFromTicketInspector MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = 4172547533
)
var values_MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues = map[MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues]string{
	0x236d0520: "electronic_pdf_from_app",
	0x54a5b34d: "thermal_paper_from_emke",
	0x691b8d67: "hologram_paper_from_volanbusz",
	0xa7d59ea6: "paper_from_vending_machine",
	0xc785b60c: "paper_bkk_pass",
	0x338797fe: "electronic_pdf_from_web",
	0xf8b405cd: "thermal_paper_from_ticket_inspector",
}
func (v MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues) String() string {
	s, _ := values_MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues[v]
	return s
}
type MavTrainTicketPayload_TicketMedium struct {
	Tag  MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues
	Name string
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload_Header
}
func NewMavTrainTicketPayload_TicketMedium() *MavTrainTicketPayload_TicketMedium {
	return &MavTrainTicketPayload_TicketMedium{
	}
}

func (this MavTrainTicketPayload_TicketMedium) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_TicketMedium) Read(io *kaitai.Stream, parent *MavTrainTicketPayload_Header, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp47, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.Tag = MavTrainTicketPayload_TicketMedium_TicketMediumKnownValues(tmp47)
	this.Name = this.Tag.String()
	return err
}

/**
 * Timestamps are represented as the number of seconds since
 * 2017-01-01T00:00:00+01:00, as 32 bit integer.
 */
type MavTrainTicketPayload_Timestamp struct {
	SecondsSince2017 uint32
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent kaitai.Struct
	_f_secondsSince1970 bool
	SecondsSince1970 int
}
func NewMavTrainTicketPayload_Timestamp() *MavTrainTicketPayload_Timestamp {
	return &MavTrainTicketPayload_Timestamp{
	}
}

func (this MavTrainTicketPayload_Timestamp) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_Timestamp) Read(io *kaitai.Stream, parent kaitai.Struct, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp48, err := this._io.ReadU4be()
	if err != nil {
		return err
	}
	this.SecondsSince2017 = uint32(tmp48)

	this.SecondsSince1970 = int(this.SecondsSince2017 + 1483225200)

	return err
}

type MavTrainTicketPayload_TripBlock struct {
	TicketKind *MavTrainTicketPayload_TicketKind
	DepartureStation *MavTrainTicketPayload_StationId
	DestinationStation *MavTrainTicketPayload_StationId
	ViaStations []*MavTrainTicketPayload_StationId
	Class string
	IsRealTicket uint8
	ValidStartAt *MavTrainTicketPayload_Timestamp
	ValidInterval *MavTrainTicketPayload_ValidInterval
	NumPassengers uint8
	AppliedDiscounts *MavTrainTicketPayload_AppliedDiscounts
	Version uint8
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent *MavTrainTicketPayload
}
func NewMavTrainTicketPayload_TripBlock(version uint8) *MavTrainTicketPayload_TripBlock {
	return &MavTrainTicketPayload_TripBlock{
		Version: version,
	}
}

func (this MavTrainTicketPayload_TripBlock) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_TripBlock) Read(io *kaitai.Stream, parent *MavTrainTicketPayload, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	tmp49 := NewMavTrainTicketPayload_TicketKind()
	err = tmp49.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.TicketKind = tmp49
	tmp50 := NewMavTrainTicketPayload_StationId(this.Version)
	err = tmp50.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DepartureStation = tmp50
	tmp51 := NewMavTrainTicketPayload_StationId(this.Version)
	err = tmp51.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.DestinationStation = tmp51
	for i := 0; i < int(30); i++ {
		_ = i
		tmp52 := NewMavTrainTicketPayload_StationId(this.Version)
		err = tmp52.Read(this._io, this, this._root)
		if err != nil {
			return err
		}
		if tmp52.Id != 0 {
			this.ViaStations = append(this.ViaStations, tmp52)
		}
	}
	tmp53, err := this._io.ReadBytes(int(1))
	if err != nil {
		return err
	}
	tmp53 = tmp53
	this.Class = string(tmp53)
	tmp54, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.IsRealTicket = tmp54
	tmp55 := NewMavTrainTicketPayload_Timestamp()
	err = tmp55.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidStartAt = tmp55
	tmp56 := NewMavTrainTicketPayload_ValidInterval(this.Version)
	err = tmp56.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.ValidInterval = tmp56
	tmp57, err := this._io.ReadU1()
	if err != nil {
		return err
	}
	this.NumPassengers = tmp57
	tmp58 := NewMavTrainTicketPayload_AppliedDiscounts()
	err = tmp58.Read(this._io, this, this._root)
	if err != nil {
		return err
	}
	this.AppliedDiscounts = tmp58
	return err
}
type MavTrainTicketPayload_ValidInterval struct {
	Minutes int
	Version uint8
	_io *kaitai.Stream
	_root *MavTrainTicketPayload
	_parent kaitai.Struct
}
func NewMavTrainTicketPayload_ValidInterval(version uint8) *MavTrainTicketPayload_ValidInterval {
	return &MavTrainTicketPayload_ValidInterval{
		Version: version,
	}
}

func (this MavTrainTicketPayload_ValidInterval) IO_() *kaitai.Stream {
	return this._io
}

func (this *MavTrainTicketPayload_ValidInterval) Read(io *kaitai.Stream, parent kaitai.Struct, root *MavTrainTicketPayload) (err error) {
	this._io = io
	this._parent = parent
	this._root = root

	switch (this.Version) {
	case 2:
		tmp59, err := this._io.ReadU2be()
		if err != nil {
			return err
		}
		this.Minutes = int(tmp59)
	case 3:
		tmp60, err := this._io.ReadU2be()
		if err != nil {
			return err
		}
		this.Minutes = int(tmp60)
	default:
		tmp61, err := this._io.ReadBitsIntBe(24)
		if err != nil {
			return err
		}
		this.Minutes = int(tmp61)
	}
	return err
}
